# Generated by Django 6.0.2 on 2026-02-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('user', 'day_of_week', 'time_slot')},
        ),
    ]
