# Generated by Django 6.0.2 on 2026-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_availability_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='quaran_memorization_folder/'),
        ),
    ]
