# Generated by Django 6.0.2 on 2026-02-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
