# Generated by Django 6.0.2 on 2026-02-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_videocall'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_streak_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
