# Generated by Django 6.0.2 on 2026-03-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_last_streak_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
