# Generated by Django 6.0.2 on 2026-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_useraccount_is_2fa_enabled_useraccount_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
