// All world languages (most commonly spoken)
export const LANGUAGES = [
    'Arabic',
    'Bengali',
    'Chinese (Mandarin)',
    'Chinese (Cantonese)',
    'Dutch',
    'English',
    'French',
    'German',
    'Hindi',
    'Indonesian',
    'Italian',
    'Japanese',
    'Korean',
    'Malay',
    'Persian (Farsi)',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Russian',
    'Spanish',
    'Swahili',
    'Tamil',
    'Telugu',
    'Thai',
    'Turkish',
    'Ukrainian',
    'Urdu',
    'Vietnamese',
    'Afrikaans',
    'Albanian',
    'Amharic',
    'Armenian',
    'Azerbaijani',
    'Basque',
    'Belarusian',
    'Bosnian',
    'Bulgarian',
    'Burmese',
    'Catalan',
    'Cebuano',
    'Chichewa',
    'Croatian',
    'Czech',
    'Danish',
    'Estonian',
    'Filipino (Tagalog)',
    'Finnish',
    'Georgian',
    'Greek',
    'Gujarati',
    'Haitian Creole',
    'Hausa',
    'Hebrew',
    'Hungarian',
    'Icelandic',
    'Igbo',
    'Irish',
    'Javanese',
    'Kannada',
    'Kazakh',
    'Khmer',
    'Kurdish',
    'Kyrgyz',
    'Lao',
    'Latin',
    'Latvian',
    'Lithuanian',
    'Luxembourgish',
    'Macedonian',
    'Malagasy',
    'Malayalam',
    'Maltese',
    'Maori',
    'Marathi',
    'Mongolian',
    'Nepali',
    'Norwegian',
    'Pashto',
    'Romanian',
    'Samoan',
    'Serbian',
    'Sesotho',
    'Shona',
    'Sindhi',
    'Sinhala',
    'Slovak',
    'Slovenian',
    'Somali',
    'Sundanese',
    'Swedish',
    'Tajik',
    'Tigrinya',
    'Tswana',
    'Turkmen',
    'Uzbek',
    'Welsh',
    'Xhosa',
    'Yiddish',
    'Yoruba',
    'Zulu'
].sort();

const BASE_TIMEZONES = [
    { offset: '-12:00', label: 'Baker Island' },
    { offset: '-11:00', label: 'American Samoa' },
    { offset: '-10:00', label: 'Hawaii' },
    { offset: '-09:30', label: 'Marquesas Islands' },
    { offset: '-09:00', label: 'Alaska' },
    { offset: '-08:00', label: 'Pacific Time (US & Canada)' },
    { offset: '-07:00', label: 'Mountain Time (US & Canada)' },
    { offset: '-06:00', label: 'Central Time (US & Canada)' },
    { offset: '-05:00', label: 'Eastern Time (US & Canada)' },
    { offset: '-04:00', label: 'Atlantic Time (Canada)' },
    { offset: '-03:30', label: 'Newfoundland' },
    { offset: '-03:00', label: 'Buenos Aires, Brasilia' },
    { offset: '-02:00', label: 'Mid-Atlantic' },
    { offset: '-01:00', label: 'Azores' },
    { offset: '+00:00', label: 'London, Dublin, Lisbon' },
    { offset: '+01:00', label: 'Paris, Berlin, Rome' },
    { offset: '+02:00', label: 'Cairo, Athens, Helsinki' },
    { offset: '+03:00', label: 'Moscow, Istanbul, Riyadh' },
    { offset: '+03:30', label: 'Tehran' },
    { offset: '+04:00', label: 'Dubai, Baku' },
    { offset: '+04:30', label: 'Kabul' },
    { offset: '+05:00', label: 'Karachi, Tashkent' },
    { offset: '+05:30', label: 'New Delhi, Mumbai, Kolkata' },
    { offset: '+05:45', label: 'Kathmandu' },
    { offset: '+06:00', label: 'Dhaka, Almaty' },
    { offset: '+06:30', label: 'Yangon' },
    { offset: '+07:00', label: 'Bangkok, Jakarta, Hanoi' },
    { offset: '+08:00', label: 'Beijing, Singapore, Perth' },
    { offset: '+08:45', label: 'Eucla' },
    { offset: '+09:00', label: 'Tokyo, Seoul' },
    { offset: '+09:30', label: 'Adelaide, Darwin' },
    { offset: '+10:00', label: 'Sydney, Melbourne, Brisbane' },
    { offset: '+10:30', label: 'Lord Howe Island' },
    { offset: '+11:00', label: 'Solomon Islands' },
    { offset: '+12:00', label: 'Fiji, Auckland' },
    { offset: '+12:45', label: 'Chatham Islands' },
    { offset: '+13:00', label: 'Tonga, Samoa' },
    { offset: '+14:00', label: 'Line Islands' }
];

// All world timezones
export const TIMEZONES = BASE_TIMEZONES.map(({ offset, label }) => 
    `(GMT${offset}) ${label}`
);

// Comprehensive list of countries for location selection
export const LOCATIONS = [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
    'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
    'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo (Congo-Brazzaville)', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia (Czech Republic)',
    'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
    'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
    'Fiji', 'Finland', 'France',
    'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
    'Haiti', 'Honduras', 'Hungary',
    'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
    'Jamaica', 'Japan', 'Jordan',
    'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
    'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
    'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar (formerly Burma)',
    'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway',
    'Oman',
    'Pakistan', 'Palau', 'Palestine State', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
    'Qatar',
    'Romania', 'Russia', 'Rwanda',
    'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
    'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
    'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan',
    'Vanuatu', 'Venezuela', 'Vietnam',
    'Yemen',
    'Zambia', 'Zimbabwe'
].sort();
