// All world languages (most commonly spoken)
export const LANGUAGES = [
    'Arabic',
    'Bengali',
    'Chinese (Mandarin)',
    'Chinese (Cantonese)',
    'Dutch',
    'English',
    'French',
    'German',
    'Hindi',
    'Indonesian',
    'Italian',
    'Japanese',
    'Korean',
    'Malay',
    'Persian (Farsi)',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Russian',
    'Spanish',
    'Swahili',
    'Tamil',
    'Telugu',
    'Thai',
    'Turkish',
    'Ukrainian',
    'Urdu',
    'Vietnamese',
    'Afrikaans',
    'Albanian',
    'Amharic',
    'Armenian',
    'Azerbaijani',
    'Basque',
    'Belarusian',
    'Bosnian',
    'Bulgarian',
    'Burmese',
    'Catalan',
    'Cebuano',
    'Chichewa',
    'Croatian',
    'Czech',
    'Danish',
    'Estonian',
    'Filipino (Tagalog)',
    'Finnish',
    'Georgian',
    'Greek',
    'Gujarati',
    'Haitian Creole',
    'Hausa',
    'Hebrew',
    'Hungarian',
    'Icelandic',
    'Igbo',
    'Irish',
    'Javanese',
    'Kannada',
    'Kazakh',
    'Khmer',
    'Kurdish',
    'Kyrgyz',
    'Lao',
    'Latin',
    'Latvian',
    'Lithuanian',
    'Luxembourgish',
    'Macedonian',
    'Malagasy',
    'Malayalam',
    'Maltese',
    'Maori',
    'Marathi',
    'Mongolian',
    'Nepali',
    'Norwegian',
    'Pashto',
    'Romanian',
    'Samoan',
    'Serbian',
    'Sesotho',
    'Shona',
    'Sindhi',
    'Sinhala',
    'Slovak',
    'Slovenian',
    'Somali',
    'Sundanese',
    'Swedish',
    'Tajik',
    'Tigrinya',
    'Tswana',
    'Turkmen',
    'Uzbek',
    'Welsh',
    'Xhosa',
    'Yiddish',
    'Yoruba',
    'Zulu'
].sort();

// All world timezones
export const TIMEZONES = [
    'UTC-12:00 (Baker Island)',
    'UTC-11:00 (American Samoa)',
    'UTC-10:00 (Hawaii)',
    'UTC-09:30 (Marquesas Islands)',
    'UTC-09:00 (Alaska)',
    'UTC-08:00 (Pacific Time - US & Canada)',
    'UTC-07:00 (Mountain Time - US & Canada)',
    'UTC-06:00 (Central Time - US & Canada)',
    'UTC-05:00 (Eastern Time - US & Canada)',
    'UTC-04:00 (Atlantic Time - Canada)',
    'UTC-03:30 (Newfoundland)',
    'UTC-03:00 (Buenos Aires, Brasilia)',
    'UTC-02:00 (Mid-Atlantic)',
    'UTC-01:00 (Azores)',
    'UTC+00:00 (London, Dublin, Lisbon)',
    'UTC+01:00 (Paris, Berlin, Rome)',
    'UTC+02:00 (Cairo, Athens, Helsinki)',
    'UTC+03:00 (Moscow, Istanbul, Riyadh)',
    'UTC+03:30 (Tehran)',
    'UTC+04:00 (Dubai, Baku)',
    'UTC+04:30 (Kabul)',
    'UTC+05:00 (Karachi, Tashkent)',
    'UTC+05:30 (New Delhi, Mumbai, Kolkata)',
    'UTC+05:45 (Kathmandu)',
    'UTC+06:00 (Dhaka, Almaty)',
    'UTC+06:30 (Yangon)',
    'UTC+07:00 (Bangkok, Jakarta, Hanoi)',
    'UTC+08:00 (Beijing, Singapore, Perth)',
    'UTC+08:45 (Eucla)',
    'UTC+09:00 (Tokyo, Seoul)',
    'UTC+09:30 (Adelaide, Darwin)',
    'UTC+10:00 (Sydney, Melbourne, Brisbane)',
    'UTC+10:30 (Lord Howe Island)',
    'UTC+11:00 (Solomon Islands)',
    'UTC+12:00 (Fiji, Auckland)',
    'UTC+12:45 (Chatham Islands)',
    'UTC+13:00 (Tonga, Samoa)',
    'UTC+14:00 (Line Islands)'
].sort();
